# Generated by Django 2.2.3 on 2019-07-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='inflow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='outflow',
            field=models.FloatField(default=0),
        ),
    ]
