# Generated by Django 2.2.3 on 2019-07-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='isPublic',
            field=models.BooleanField(),
        ),
    ]
